spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  message: ${APP_MESSAGE:Hello from Kubernetes}
